version: 2.1

# Think of orbs as libraries or packages for CircleCI
orbs:
  slack: circleci/slack@4.4.4
  aws-cli: circleci/aws-cli@2.0.3

# These are custom functions that I use in other jobs
commands:
  # Function 1
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1 # build in formating template to display failure
          mentions: "@ugochi" #if you want to target a particular person
          channel: alerts # Slack channel to display to

  # Function 2
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      # Add parameter here
      workflow_id:
        type: string
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            # Your code here
            # Use for roll back
            # Delete any infrastructure created.

            #echo s3://udapeople-<<parameters.workflow_id>>/
            #echo uda-frontend-stack-<<parameters.workflow_id>>
            
            #aws s3 rm --recursive s3://udapeople-<<parameters.workflow_id>>/
            #aws s3 rb s3://udapeople-<<parameters.workflow_id>> --force
            #aws cloudformation delete-stack --stack-name "uda-frontend-stack-<<parameters.workflow_id>>"
            #aws cloudformation delete-stack --stack-name "uda-backend-stack-<<parameters.workflow_id>>"
            #aws cloudformation delete-stack --stack-name uda-prometheus-server-stack

jobs:
  build:
    docker: 
      # This image has poetry, pyenv, pip, pipenv, and python 3.10 pre-installed
      # https://hub.docker.com/r/cimg/python
      - image: cimg/python
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pyproject.toml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Tools & Dependencies
          command: |
            
            # Create Environment
            python -m venv capstone
            . capstone/bin/activate

            # Check linux operating system of docker container
            cat /etc/os-release

            # install tools
            make setup

            # Install python packages
            make install

      - save_cache:
          paths:
            - ./capstone
          key: v1-dependencies-{{ checksum "pyproject.toml" }}
      
      # run lint!
      - run:
          name: run lint
          command: |
            . capstone/bin/activate
            cd dagster_capstone/dagster_capstone
            make lint

      # run test
      - run:
          name: run dagster tests
          command: |
            # Your code here.
            # @@@ I would put this in its own job
            echo "implement tests and move to it's own job"

      #- slack/notify # I need to add a SLACK TOKEN to enable this.

  #build_docker_image:

workflows:
  default:
    jobs:
      - build
      #- lint:
      #    requires: [build]