# Reference
# ---------
# Create a Service. A Service allows you to access all replicas through a single IP address or name. 
#
# Multi-Port Services: https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
apiVersion: v1
kind: Service
metadata:
  # name of the service
  name: dagster 
spec:
  # Has to match name and version
  selector:
    app: dagster
    version: v1.0.0
  type: LoadBalancer # Open traffic to outside traffix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000