# Reference
# ---------
# Create a Service. A Service allows you to access all replicas through a single IP address or name. 
#
# Multi-Port Services: https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
apiVersion: v1
kind: Service
metadata:
  name: dagster
spec:
  selector:
    app: dagster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000