# Reference
# ---------
#
# Multi-Port Services: https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
apiVersion: v1
kind: Service
metadata:
  name: dagster
spec:
  ports:
    - port: 3000
      name: dagit
    # - port: 5432
    #   name: postgres
  selector:
    app: dagster
  clusterIP: None